// Estado del ecosistema · qué se ha generado en cada módulo + actividad reciente.

export const ECOSYSTEM_METRICS = [
  {
    id: "pieces",
    label: "Piezas generadas",
    value: "142",
    delta: "+18 esta semana",
    deltaTone: "up",
    accent: "from-[#00e5ff] to-[#4f8cff]",
  },
  {
    id: "ads",
    label: "Ads en rotación",
    value: "47",
    delta: "+12 vs. mes anterior",
    deltaTone: "up",
    accent: "from-[#8a5cff] to-[#ff3d71]",
  },
  {
    id: "leads",
    label: "Leads cualificados",
    value: "318",
    delta: "+62 esta semana",
    deltaTone: "up",
    accent: "from-[#00ffd1] to-[#00e5ff]",
  },
  {
    id: "roas",
    label: "ROAS medio",
    value: "3.42x",
    delta: "+0.4 vs. mes anterior",
    deltaTone: "up",
    accent: "from-[#ffcc33] to-[#ff6b35]",
  },
];

export const MODULE_CARDS = [
  {
    id: "contenido-largo",
    pillar: "Contenido",
    title: "Largo",
    description: "Posts largos, artículos, VSL y dossieres",
    href: "/dashboard/contenido/largo",
    generated: 28,
    metric: "Score medio 87",
    status: "Activo",
    statusTone: "success",
    icon: "ScrollText",
    accent: "from-[#00e5ff] to-[#4f8cff]",
  },
  {
    id: "contenido-corto",
    pillar: "Contenido",
    title: "Corto · Hooks",
    description: "8 hooks por ciclo · 6 frameworks ganadores",
    href: "/dashboard/contenido/corto",
    generated: 64,
    metric: "12 cargados a Buffer",
    status: "Generando",
    statusTone: "neon",
    icon: "Type",
    accent: "from-[#00ffd1] to-[#00e5ff]",
  },
  {
    id: "ads-estaticos",
    pillar: "Ads",
    title: "Estáticos",
    description: "6 formatos ganadores · batches de 9-18",
    href: "/dashboard/ads/estaticos",
    generated: 27,
    metric: "Top format · Bold Stat",
    status: "Activo",
    statusTone: "success",
    icon: "ImageIcon",
    accent: "from-[#4f8cff] to-[#8a5cff]",
  },
  {
    id: "ads-videos-directa",
    pillar: "Ads",
    title: "Vídeo · Of. Directa",
    description: "Storyboards 15-90s · hook + prueba + CTA",
    href: "/dashboard/ads/videos/directa",
    generated: 14,
    metric: "Framework top · 3-Sec Promise",
    status: "Activo",
    statusTone: "success",
    icon: "Send",
    accent: "from-[#8a5cff] to-[#ff3d71]",
  },
  {
    id: "ads-videos-indirecta",
    pillar: "Ads",
    title: "Vídeo · Of. Indirecta",
    description: "Educativos 60s-10min · valor primero",
    href: "/dashboard/ads/videos/indirecta",
    generated: 9,
    metric: "Lección top · 'cohortes'",
    status: "Borrador",
    statusTone: "violet",
    icon: "GraduationCap",
    accent: "from-[#ff6b35] to-[#ffcc33]",
  },
  {
    id: "funnels-compra-vsl",
    pillar: "Funnels",
    title: "Landing · Compra VSL",
    description: "VSL + value stack + garantía",
    href: "/dashboard/funnels/landings/compra/vsl",
    generated: 6,
    metric: "Conversión · 6.1%",
    status: "Publicado",
    statusTone: "success",
    icon: "Sparkles",
    accent: "from-[#00e5ff] to-[#00ffd1]",
  },
  {
    id: "funnels-compra-largo",
    pillar: "Funnels",
    title: "Landing · Compra Largo",
    description: "Long-form sin VSL · tráfico frío",
    href: "/dashboard/funnels/landings/compra/largo",
    generated: 4,
    metric: "Scroll 80% · 47%",
    status: "Test A/B",
    statusTone: "neon",
    icon: "ScrollText",
    accent: "from-[#ffcc33] to-[#ff6b35]",
  },
  {
    id: "funnels-compra-dossier",
    pillar: "Funnels",
    title: "Landing · Dossier",
    description: "Editorial · ticket alto · B2B",
    href: "/dashboard/funnels/landings/compra/dossier",
    generated: 3,
    metric: "Conversión · 4.2%",
    status: "Publicado",
    statusTone: "success",
    icon: "FileStack",
    accent: "from-[#00ffd1] to-[#00e5ff]",
  },
  {
    id: "funnels-optin-vsl",
    pillar: "Funnels",
    title: "Opt-in · VSL",
    description: "Webinar + lead magnet",
    href: "/dashboard/funnels/landings/optin/vsl",
    generated: 5,
    metric: "Opt-in rate · 52%",
    status: "Publicado",
    statusTone: "success",
    icon: "Mail",
    accent: "from-[#8a5cff] to-[#4f8cff]",
  },
  {
    id: "funnels-optin-largo",
    pillar: "Funnels",
    title: "Opt-in · Largo",
    description: "Long-form SEO con CTA sticky",
    href: "/dashboard/funnels/landings/optin/largo",
    generated: 2,
    metric: "Opt-in rate · 38%",
    status: "Borrador",
    statusTone: "violet",
    icon: "ScrollText",
    accent: "from-[#00ffd1] to-[#8a5cff]",
  },
  {
    id: "funnels-optin-dossier",
    pillar: "Funnels",
    title: "Opt-in · Dossier",
    description: "PDF ejecutivo para ABM B2B",
    href: "/dashboard/funnels/landings/optin/dossier",
    generated: 2,
    metric: "Opt-in rate · 44%",
    status: "Publicado",
    statusTone: "success",
    icon: "FileStack",
    accent: "from-[#c3d4ff] to-[#a0aec0]",
  },
  {
    id: "funnels-upsell",
    pillar: "Funnels",
    title: "Upsell post-compra",
    description: "1 clic · timer + scarcity",
    href: "/dashboard/funnels/vsl-compra/upsell",
    generated: 3,
    metric: "Take rate · 32%",
    status: "Publicado",
    statusTone: "success",
    icon: "PlusSquare",
    accent: "from-[#ff3d71] to-[#8a5cff]",
  },
  {
    id: "funnels-bumps",
    pillar: "Funnels",
    title: "Order bumps",
    description: "Microofertas en checkout",
    href: "/dashboard/funnels/vsl-compra/bumps",
    generated: 3,
    metric: "AOV +18% medio",
    status: "Publicado",
    statusTone: "success",
    icon: "ShoppingCart",
    accent: "from-[#00e5ff] to-[#4f8cff]",
  },
];

export const ECOSYSTEM_ACTIVITY = [
  {
    id: "act-001",
    actor: "IA Eneryia",
    action: "regeneró sección",
    target: "Hero · Landing VSL Compra",
    module: "Funnels",
    time: "hace 4 min",
    tone: "neon",
  },
  {
    id: "act-002",
    actor: "Tomás J.",
    action: "publicó",
    target: "Opt-in webinar · Jueves 19h",
    module: "Funnels",
    time: "hace 12 min",
    tone: "success",
  },
  {
    id: "act-003",
    actor: "IA Eneryia",
    action: "generó batch de 9 creativos",
    target: "Ads · Estáticos · Bold Stat",
    module: "Ads",
    time: "hace 32 min",
    tone: "neon",
  },
  {
    id: "act-004",
    actor: "María L.",
    action: "marcó como favorito",
    target: "Hook · 'Si tu agenda depende de WhatsApp'",
    module: "Contenido",
    time: "hace 1h",
    tone: "violet",
  },
  {
    id: "act-005",
    actor: "Setter IA",
    action: "calificó lead",
    target: "Arnau · 28K/mes · ICP",
    module: "Pipeline",
    time: "hace 1h 24m",
    tone: "success",
  },
  {
    id: "act-006",
    actor: "IA Eneryia",
    action: "preparó storyboard",
    target: "Vídeo Directa · 30s · 3-Sec Promise",
    module: "Ads",
    time: "hace 2h",
    tone: "neon",
  },
  {
    id: "act-007",
    actor: "Iván P.",
    action: "lanzó test A/B",
    target: "Landing Compra Largo · variante B",
    module: "Funnels",
    time: "hace 3h",
    tone: "violet",
  },
  {
    id: "act-008",
    actor: "Tomás J.",
    action: "completó Brief",
    target: "Sección 'Avatar del cliente'",
    module: "Brief",
    time: "hace 5h",
    tone: "success",
  },
];

export const QUICK_ACTIONS = [
  {
    id: "qa-content",
    title: "Generar batch de hooks",
    description: "8 hooks listos para LinkedIn / X / email",
    href: "/dashboard/contenido/corto",
    cta: "Generar ahora",
    icon: "Sparkles",
  },
  {
    id: "qa-ads",
    title: "Lanzar manada de creativos",
    description: "9 ads estáticos en 4 formatos ganadores",
    href: "/dashboard/ads/estaticos",
    cta: "Generar manada",
    icon: "Megaphone",
  },
  {
    id: "qa-landing",
    title: "Montar landing VSL",
    description: "Brief inyectado · plantilla ganadora",
    href: "/dashboard/funnels/landings/compra/vsl",
    cta: "Crear landing",
    icon: "Globe",
  },
];
